version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file infrastructure/infra.yml \
            --stack-name hiwit-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1
workflows:
  prepare_infra:
    jobs:
      - create_infrastructure
    